---
- hosts: servers
  become: true

  tasks:
    - name: Update and install desired packages
      apt:
        pkg:
          - vim
          - git
        state: latest
        update_cache: yes
    
    - name: update apt
      apt:
        update_cache: yes

    - name: install docker prereqs
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: latest
        update_cache: yes
    
    - name: Add GPG Key 
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
    
    - name: Add Docker Repo
      apt_repository: 
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
    
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: verify docker is running
      systemd:
        state: started
        name: docker
    
    - name: put user in docker group
      user:
        name: joe
        groups: docker
        append: yes
    
    - name: Install python docker package
      pip:
        name: docker
    
    - name: Pull down desired images 
      community.docker.docker_image:
        name: "jellyfin/jellyfin"
        source: pull
    
    - name: Create a folder to mount the external hard drive
      file:
        path: /media/easystore
        state: directory
        mode: '0755'
    
    - name: mount the external hard drive
      ansible.posix.mount:
        path: /media/easystore
        src: /dev/sdb1
        fstype: ntfs
        state: mounted 

    - name: Create a movie folder on the drive
      file:
        path: /media/easystore/media/Movies
        state: directory
        mode: '0755'

    - name: Create a shows folder on the drive
      file:
        path: /media/easystore/media/Shows
        state: directory
        mode: '0755'

    - name: Create a cache folder on the drive
      file:
        path: /media/easystore/cache
        state: directory
        mode: '0755'

    - name: Create a config folder on the drive
      file:
        path: /media/easystore/config
        state: directory
        mode: '0755'

    - name: install samba
      apt:
        pkg:
          - samba
        state: latest
        update_cache: true

    - name: Update the samba.conf file
      blockinfile:
        path: /etc/samba/smb.conf 
        block: |
          [jellyfin]
            comment = Samba on Ubuntu
            path = /media/easystore
            read only = no
            browsable = yes

    - name: Restart the samba service
      service:
        name: smbd
        state: restarted 
    
    - name: Update the ufw firewall
      community.general.ufw:
        rule: allow
        name: samba

    - name: Add default user to the samba permissions
      shell:  "(echo {{ smbpass }}; echo {{ smbpass }}) | smbpasswd -s joe" 
      become: yes
